version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/gcp"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
